baseURL = "https://chrispanag.com/"
languageCode = "en-us"
title = "Christos Panagiotakopoulos"
theme = "coder-portfolio"
defaultcontentlanguage  = "en"

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

# disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Christos Panagiotakopoulos" # Author's name.
    info = "Back-end Engineer | Chatbots Developer" # Author's job title or info.
    description = "Backend Engineer | Chatbots Developer" # Site description.
    keywords = "blog,software,christos,panagiotakopoulos,χρήστος,παναγιωτακόπουλος,developer,personal,chatbots,engineer,backend,frontend,facebook,bots,ebony,ebony-framework,node,nodejs,javascript,typescript,greece,athens" # Site keywords.
    
    avatarurl = "images/avatar.jpg" # Contain the path of the optional avatar in the static folder.

    footercontent = "Copyright© Christos Panagiotakopoulos" # Add footer content
    fixedbarContent = "Do you want to contact me privately? → " # Add fixedbar content
    fixedbarContentAfter = "Send me an email at chrispanag@gmail.com ;)" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = [
        "custom.css"
    ]

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/thumb.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/chrispanag/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/chrispanag/"
[[params.social]]
    name = "Twitter"
    weight = 3
    url = "https://www.twitter.com/ChrisPanag"

# Menu links
#
[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "projects"
[[menu.main]]
    name = "Lectures"
    weight = 2
    url  = "lectures"

#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "about"
